name: gh-pages

on: [push, pull_request]

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
        - name: Build Sphinx
          run: |
             cd docs
             make html
             cd ..
             mkdir -p out
             mv docs/build/html/* out/
      
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./out
            keep_files: true


